# Generated by Django 3.1.4 on 2020-12-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
