# Generated by Django 3.1.4 on 2020-12-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_apply_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='vc',
            new_name='cv',
        ),
    ]
